wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1673618112.536256
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.6.13
      5: 0.13.3
      8:
      - 1
      - 5
architecture:
  desc: null
  value: RESNET
dataset:
  desc: null
  value: 596_img_cleftlip
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.0001
